export const SCRIPTURE_HOVER_PREVIEW_MODAL_WIDTH_CAP_DEFAULT_PX = 448;
export const SCRIPTURE_HOVER_PREVIEW_MODAL_WIDTH_CAP_TABLET_PX = 520;
export const SCRIPTURE_HOVER_PREVIEW_MODAL_WIDTH_CAP_DESKTOP_PX = 600;
export const SCRIPTURE_HOVER_PREVIEW_MODAL_WIDTH_BREAKPOINT_TABLET = 640;
export const SCRIPTURE_HOVER_PREVIEW_MODAL_WIDTH_BREAKPOINT_DESKTOP = 900;
export const SCRIPTURE_HOVER_PREVIEW_MODAL_LAYOUT_HEIGHT_CAP_PX = 720;
export const SCRIPTURE_HOVER_PREVIEW_PLACEMENT_PROBE_HEIGHT_PX = 520;
export const SCRIPTURE_HOVER_PREVIEW_MIN_POPOVER_MAX_HEIGHT_PX = 120;
export const SCRIPTURE_HOVER_PREVIEW_VIEWPORT_PADDING_PX = 12;
export const SCRIPTURE_HOVER_PREVIEW_ANCHOR_GAP_PX = 10;
export const SCRIPTURE_HOVER_PREVIEW_LONG_PRESS_MS = 500;
/** Cancel pending long-press when the finger moves this far (scroll gesture). */
export const SCRIPTURE_HOVER_PREVIEW_LONG_PRESS_MOVE_CANCEL_PX = 10;
/** Grace period so the pointer can cross the gap into the popover to scroll. */
export const SCRIPTURE_HOVER_PREVIEW_HOVER_HIDE_GRACE_MS = 150;
